Fixed issue #385
multivendorx/mvx pull request #534
Opened 2023-09-28 06:13 UTC by user-promi

2023-09-29 07:59 UTC, moumitahalder requested changes

2023-09-29 07:59 UTC, moumitahalder commented on classes/class-mvx-payment-gateway.php
> +                if(!current_user_can('administrator') && $commission_status == 'mvx_processing') :
checking missing

2023-09-29 08:49 UTC, abhirup97 commented on classes/class-mvx-payment-gateway.php
> +                if(!current_user_can('administrator') && $commission_status == 'mvx_processing') :
Still indentation issue

2023-09-29 09:01 UTC, abhirup97 commented
@Sangi0  test this and add tested label if working fine

2023-09-30 11:57 UTC, moumitahalder requested changes

2023-09-30 11:57 UTC, moumitahalder commented on classes/class-mvx-payment-gateway.php
> +                if ($commission_status) {
why extra line for checking?

2023-09-30 11:57 UTC, moumitahalder commented
do a fresh commit @user-promi

2023-09-30 12:07 UTC, closed without merging