fixed issue #548
multivendorx/mvx pull request #551
Opened 2023-10-14 12:07 UTC by user-promi

2023-10-26 15:09 UTC, moumitahalder requested changes

2023-10-26 15:09 UTC, moumitahalder commented on classes/class-mvx-product.php
> +            $related = get_mvx_global_settings('show_related_products') ? mvx_get_settings_value(get_mvx_global_settings('show_related_products') ): '';
indentation

2023-10-26 15:33 UTC, user-promi commented
Done

2023-10-27 06:02 UTC, Sangi0 commented
https://watch.screencastify.com/v/Eb6bUkBLrvxQ38VxwVxB

2023-10-28 08:56 UTC, closed without merging