Added #553
multivendorx/mvx pull request #554
Opened 2023-10-19 11:04 UTC by user-promi

2023-10-19 13:17 UTC, Sangi0 commented
https://watch.screencastify.com/v/xn54P4yMFjtkmE9EIDfc

2023-10-26 15:07 UTC, moumitahalder requested changes

2023-10-26 15:07 UTC, moumitahalder commented on api/class-mvx-rest-controller.php
> +        if ($this->mvx_list_of_request_profile_deletion_vendor()->data && !empty($this->mvx_list_of_request_profile_deletion_vendor()->data)) {
checking missing

2023-10-26 15:07 UTC, moumitahalder commented on api/class-mvx-rest-controller.php
> +                    $email = WC()->mailer()->emails['WC_Email_Vendor_Account_Deletion_Mail'];
checking needed

2023-10-26 15:07 UTC, moumitahalder commented on api/class-mvx-rest-controller.php
> +                    $email->trigger($vendor_id);
checking needed

2023-10-26 15:07 UTC, moumitahalder commented on api/class-mvx-rest-controller.php
> +            if ($this->mvx_list_of_request_profile_deletion_vendor()->data && !empty($this->mvx_list_of_request_profile_deletion_vendor()->data)) {
checking

2023-10-26 15:07 UTC, moumitahalder commented on mvx-modules/src/components/admin/classes/class-mvx-workboard-section.js
> +						list_of_work_board_content: response.data,
checking

2023-10-26 15:08 UTC, moumitahalder commented
few reviews given. please go through the code thoroughly

2023-10-28 08:56 UTC, closed without merging