Fixed #591
multivendorx/mvx pull request #593
Opened 2023-11-20 10:17 UTC by user-promi

2023-11-20 11:29 UTC, Sangi0 commented
https://watch.screencastify.com/v/zBpzDow9sc1p5r0lYn9q

2023-11-25 14:17 UTC, moumitahalder requested changes

2023-11-25 14:17 UTC, moumitahalder commented on classes/class-mvx-calculate-commission.php
> +                        if ($vendor_commission != '') {
why like ds? any functions exist or not?

2023-11-27 10:35 UTC, user-promi commented
I didn't use the empty function because 0 can come in the variable, so i used the strlen function

2023-12-07 16:17 UTC, moumitahalder requested changes

2023-12-07 16:17 UTC, moumitahalder commented on classes/class-mvx-calculate-commission.php
> +                        if (strlen($vendor_commission) > 0) {
is $vendor_commission return string?

2023-12-12 16:13 UTC, merged